### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './support/do_not_auto.txt'

### ISSUE THREAD

**Issue by dibble9012** [Coltonton/eon-custom-themes#15]
When trying to run "install_theme.py, I get this error message. "FileNotFoundError: [Errno 2] No such file or directory: './support/do_not_auto.txt'"

When lookin in folder /data/eon-custom-themes/support, there is indeed a file with the name do_not_auto.txt, with a 0 inside. I have tried changing it to a 1, as well as making the support file hidden (putting a period before it), and it still comes up with the same error. Also tried deleting the entire folder and pulling from GitHub again.

Running on a Comma2, running 0.7.10 kegman fork.

**Comment by Coltonton** [comment]
After discussion on discord with @dibble9012 issue resolved as not running the program as `exec ./install_theme.py` and instead using `./install_theme.py` which is not the same causing the program not to run correctly.  

Thank You,
